# Generated by Django 5.0.2 on 2024-03-11 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('users', '0002_role_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_org', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_org', to='organization.organization'),
        ),
    ]
